// packages/sdk-vue/playground/src/App.vue
<script setup lang="ts">
import { useReviews } from '@reviewskits/vue'

const { data, isLoading, error } = useReviews({ formId: 'rk_frm_live_72330eb710b17f3baa56d87f' })
</script>

<template>
  <div class="playground">
    <h1>ReviewsKit SDK Playground</h1>
    
    <div v-if="isLoading">Chargement des avis...</div>
    <div v-else-if="error">Erreur: {{ error }}</div>
    <div v-else-if="data">
      <h2>Avis ({{ data.reviews.length }})</h2>
      <ul>
        <li v-for="review in data.reviews" :key="review.id">
          <strong>{{ review.author.name }}</strong>: {{ review.content }}
        </li>
      </ul>
    </div>
    <div v-else>Aucun avis trouvé.</div>
  </div>
</template>

<style scoped>
.playground {
  padding: 2rem;
  max-width: 800px;
  margin: 0 auto;
}
</style>

// packages/sdk-react/playground/src/App.tsx
import { useReviews } from '@reviewskits/react'

function App() {
  const { data, isLoading, error } = useReviews({ 
    formId: 'rk_frm_live_72330eb710b17f3baa56d87f' 
  })

  return (
    <div style={{ padding: '2rem', fontFamily: 'sans-serif' }}>
      <h1>React SDK Playground</h1>
      
      {isLoading && <p>Loading reviews...</p>}
      
      {error && (
        <div style={{ color: 'red', padding: '1rem', border: '1px solid red' }}>
          <h3>Error</h3>
          <p>{error.message}</p>
          {error.details && <pre>{JSON.stringify(error.details, null, 2)}</pre>}
        </div>
      )}

      <div style={{ display: 'grid', gap: '1rem', marginTop: '2rem' }}>
        {data?.reviews.map((review: any) => (
          <div key={review.id} style={{ padding: '1rem', border: '1px solid #ddd', borderRadius: '8px' }}>
            <div style={{ fontWeight: 'bold' }}>{review.author.name}</div>
            <div style={{ color: '#666', fontSize: '0.9rem' }}>{review.author.title}</div>
            <div style={{ marginTop: '0.5rem' }}>{"★".repeat(review.rating)}{"☆".repeat(5-review.rating)}</div>
            <p>{review.content}</p>
          </div>
        ))}
      </div>
    </div>
  )
}

export default App
